import AppKit
import AintoCore

/// Monitors the system clipboard for changes every 500ms.
/// Reference: Maccy/Raycast poll NSPasteboard.general.changeCount.
///
/// All pasteboard access runs on a private serial queue, never the main thread.
/// Some clipboard items carry promised/lazy data: the bytes are produced by the
/// source app on demand when the item is first read. If that provider is slow,
/// or has died (the read then blocks until the pasteboard daemon times out), a
/// synchronous read stalls the calling thread. On the main thread that freezes
/// the whole UI, so reads must stay off it. The poll re-schedules itself only
/// after each check returns, so a slow read can never pile up a backlog.
@MainActor
final class ClipboardMonitor {
    var onClipboardChanged: (() -> Void)?

    /// Owns every pasteboard read and the mutable state below.
    private let pollQueue = DispatchQueue(label: "app.ainto.clipboard-poll", qos: .utility)
    private nonisolated static let pollInterval: TimeInterval = 0.5

    /// Touched only on `pollQueue`; serial execution guarantees exclusive access.
    private nonisolated(unsafe) var lastChangeCount = 0
    private nonisolated(unsafe) var isRunning = false

    /// Pasteboard types that indicate sensitive/transient data (should be skipped).
    private nonisolated static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    func startMonitoring() {
        pollQueue.async { [weak self] in
            guard let self, !self.isRunning else { return }
            self.isRunning = true
            self.lastChangeCount = NSPasteboard.general.changeCount
            self.scheduleNextCheck()
        }
    }

    func stopMonitoring() {
        pollQueue.async { [weak self] in
            self?.isRunning = false
        }
    }

    /// Schedules the next poll on `pollQueue`, but only once the current check
    /// has returned — so a blocked read never enqueues a backlog of checks.
    private nonisolated func scheduleNextCheck() {
        pollQueue.asyncAfter(deadline: .now() + Self.pollInterval) { [weak self] in
            guard let self, self.isRunning else { return }
            self.checkClipboard()
            self.scheduleNextCheck()
        }
    }

    /// Runs on `pollQueue`, never the main thread.
    private nonisolated func checkClipboard() {
        let pasteboard = NSPasteboard.general
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        // Check for transient/concealed types (password managers, etc.)
        if let types = pasteboard.types {
            let typeStrings = Set(types.map(\.rawValue))
            if !typeStrings.isDisjoint(with: Self.transientTypes) {
                return // Skip sensitive clipboard content
            }
        }

        // Get source app bundle ID
        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        var didInsert = false

        // Try file URL (Finder copy). Copying a link from a browser also puts a
        // `public.url` on the pasteboard, so match on file URLs specifically —
        // otherwise a copied web link inserts nothing yet still short-circuits
        // the text branch below, and never reaches the history.
        let fileURLs = (pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL])?
            .filter(\.isFileURL) ?? []
        if !fileURLs.isEmpty {
            for url in fileURLs {
                let _ = rc_clipboard_insert_file(url.path, sourceApp)
            }
            didInsert = true
        }

        // Try to read text content
        else if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let _ = rc_clipboard_insert_text(text, sourceApp)
            didInsert = true
        }

        // Try to read image content (PNG)
        else if let imageData = pasteboard.data(forType: .png) {
            imageData.withUnsafeBytes { buffer in
                guard let ptr = buffer.baseAddress?.assumingMemoryBound(to: UInt8.self) else { return }
                let _ = rc_clipboard_insert_image(ptr, UInt64(imageData.count), 0, 0, sourceApp)
            }
            didInsert = true
        }

        // Try TIFF (screenshots are often TIFF)
        else if let tiffData = pasteboard.data(forType: .tiff),
           let bitmap = NSBitmapImageRep(data: tiffData),
           let pngData = bitmap.representation(using: .png, properties: [:]) {
            pngData.withUnsafeBytes { buffer in
                guard let ptr = buffer.baseAddress?.assumingMemoryBound(to: UInt8.self) else { return }
                let width = UInt32(bitmap.pixelsWide)
                let height = UInt32(bitmap.pixelsHigh)
                let _ = rc_clipboard_insert_image(ptr, UInt64(pngData.count), width, height, sourceApp)
            }
            didInsert = true
        }

        if didInsert {
            Task { @MainActor [weak self] in
                self?.onClipboardChanged?()
            }
        }
    }
}
