import AppKit
import AintoCore

/// Monitors the system clipboard for changes every 500ms.
/// Reference: Maccy/Raycast poll NSPasteboard.general.changeCount.
///
/// All pasteboard access runs on a private serial queue, never the main thread.
/// Some clipboard items carry promised/lazy data: the bytes are produced by the
/// source app on demand when the item is first read. If that provider is slow,
/// or has died (the read then blocks until the pasteboard daemon times out), a
/// synchronous read stalls the calling thread. On the main thread that freezes
/// the whole UI, so reads must stay off it. The poll re-schedules itself only
/// after each check returns, so a slow read can never pile up a backlog.
@MainActor
final class ClipboardMonitor {
    var onClipboardChanged: (() -> Void)?

    /// Owns every pasteboard read and the mutable state below.
    private let pollQueue = DispatchQueue(label: "app.ainto.clipboard-poll", qos: .utility)
    private nonisolated static let pollInterval: TimeInterval = 0.5

    /// Touched only on `pollQueue`; serial execution guarantees exclusive access.
    private nonisolated(unsafe) var lastChangeCount = 0
    private nonisolated(unsafe) var isRunning = false

    /// Pasteboard types that indicate sensitive/transient data (should be skipped).
    private nonisolated static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    func startMonitoring() {
        pollQueue.async { [weak self] in
            guard let self, !self.isRunning else { return }
            self.isRunning = true
            self.lastChangeCount = PasteboardAccess.withPasteboard { $0.changeCount }
            self.scheduleNextCheck()
        }
    }

    func stopMonitoring() {
        pollQueue.async { [weak self] in
            self?.isRunning = false
        }
    }

    /// Schedules the next poll on `pollQueue`, but only once the current check
    /// has returned — so a blocked read never enqueues a backlog of checks.
    private nonisolated func scheduleNextCheck() {
        pollQueue.asyncAfter(deadline: .now() + Self.pollInterval) { [weak self] in
            guard let self, self.isRunning else { return }
            self.checkClipboard()
            self.scheduleNextCheck()
        }
    }

    private enum CapturedContent: Sendable {
        case files([String])
        case text(String)
        case image(Data, width: UInt32, height: UInt32)
    }

    /// Runs on `pollQueue`, never the main thread.
    private nonisolated func checkClipboard() {
        let captured: CapturedContent? = PasteboardAccess.withPasteboard { pasteboard in
            let currentCount = pasteboard.changeCount
            guard currentCount != lastChangeCount else { return nil }
            lastChangeCount = currentCount

            // Check for transient/concealed types (password managers, etc.)
            if let types = pasteboard.types {
                let typeStrings = Set(types.map(\.rawValue))
                if !typeStrings.isDisjoint(with: Self.transientTypes) {
                    return nil
                }
            }

            // Copying a browser link also includes `public.url`, so retain only
            // actual file URLs before falling back to the text representation.
            let filePaths = ((pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL]) ?? [])
                .filter(\.isFileURL)
                .map(\.path)
            if !filePaths.isEmpty {
                return .files(filePaths)
            }
            if let text = pasteboard.string(forType: .string), !text.isEmpty {
                return .text(text)
            }
            if let imageData = pasteboard.data(forType: .png) {
                return .image(imageData, width: 0, height: 0)
            }
            if let tiffData = pasteboard.data(forType: .tiff),
               let bitmap = NSBitmapImageRep(data: tiffData),
               let pngData = bitmap.representation(using: .png, properties: [:]) {
                return .image(
                    pngData,
                    width: UInt32(bitmap.pixelsWide),
                    height: UInt32(bitmap.pixelsHigh)
                )
            }
            return nil
        }
        guard let captured else { return }

        // NSWorkspace is AppKit state as well; read it on the main actor, then
        // enqueue persistence back onto the serial poll queue.
        Task { @MainActor [weak self] in
            guard let self else { return }
            let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
            self.pollQueue.async { [weak self] in
                self?.persist(captured, sourceApp: sourceApp)
            }
        }
    }

    private nonisolated func persist(_ captured: CapturedContent, sourceApp: String?) {
        switch captured {
        case .files(let paths):
            for path in paths {
                _ = rc_clipboard_insert_file(path, sourceApp)
            }
        case .text(let text):
            _ = rc_clipboard_insert_text(text, sourceApp)
        case .image(let data, let width, let height):
            data.withUnsafeBytes { buffer in
                guard let pointer = buffer.baseAddress?.assumingMemoryBound(to: UInt8.self) else { return }
                _ = rc_clipboard_insert_image(
                    pointer,
                    UInt64(data.count),
                    width,
                    height,
                    sourceApp
                )
            }
        }

        Task { @MainActor [weak self] in
            self?.onClipboardChanged?()
        }
    }
}
